# Generated by Django 3.2.9 on 2021-11-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_emailauth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailAuth',
        ),
    ]
