# Generated by Django 3.2.9 on 2021-11-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_emailauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=16)),
                ('uid', models.CharField(max_length=5)),
                ('otp', models.CharField(max_length=6)),
            ],
        ),
    ]
